name: 02 Basic Project Run Action

on:
  push:
    paths:
      - 'Code/02 Basics/02 Starting Project/**'
  pull_request:
    paths:
      - 'Code/02 Basics/02 Starting Project/**'

jobs:
  test_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.5
        
      - name: Change to specific directory
        run: cd "Code/02 Basics/02 Starting Project/"
        
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          cd "Code/02 Basics/02 Starting Project/"
          npm ci # bit safer than npm install
        
      - name: Run tests
        run: |
          cd "Code/02 Basics/02 Starting Project/"
          npm test

  deploy_stage:
    runs-on: ubuntu-latest
    needs: test_stage
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.5

      - name: Change to specific directory
        run: cd "Code/02 Basics/02 Starting Project/"
        
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd "Code/02 Basics/02 Starting Project/"
          npm ci # bit safer than npm install

      - name: Build Project
        run: |
          cd "Code/02 Basics/02 Starting Project/"
          npm run build

      - name: Deploy Project
        run: |
          echo "Deploying..."
          echo "Complete!"
